import Link from "next/link";

import { ArtworkCard } from "@/components/ArtworkCard";
import { CtaBand } from "@/components/CtaBand";
import { Hero } from "@/components/Hero";
import { MotionSection } from "@/components/MotionSection";
import { Reveal } from "@/components/Reveal";
import { SectionHeading } from "@/components/SectionHeading";
import { UiLabel } from "@/components/UiLabel";
import { FEATURED_COUPLE_ID, PHOTO } from "@/data/catalog";
import { getArtwork, getArtworks, getMedia } from "@/lib/artworks";

/** Grid sizes hint, shared by both artwork grids on this page. */
const GRID_SIZES =
  "(min-width: 1024px) 300px, (min-width: 640px) 44vw, 88vw";

/**
 * Re-read the catalogue from Supabase at most every 5 minutes.
 *
 * Without this the page is baked at build time, so editing a piece in the
 * Supabase dashboard would change nothing on the live site until the next
 * deploy — which would make the database connection decorative. Spelling
 * fixes, `featured` flags, ordering and notes now go live on their own.
 *
 * A brand-new piece still needs a deploy, because its image has to be
 * generated by `npm run assets` and shipped in public/artwork.
 */
export const revalidate = 300;

export default async function HomePage() {
  const all = await getArtworks();

  const heroArtwork =
    (await getArtwork(FEATURED_COUPLE_ID)) ??
    all.find((a) => a.kind === "couple");
  const heroMedia = heroArtwork ? getMedia(heroArtwork.id) : undefined;
  const framedPhoto = getMedia(PHOTO.framedDaylight);

  const couples = all.filter((a) => a.kind === "couple" && a.id !== heroArtwork?.id);
  const singles = all.filter((a) => a.kind === "single" && a.featured);
  const words = all.filter((a) => a.kind === "word");

  return (
    <>
      {/* 1 — the hook */}
      {heroArtwork && heroMedia && framedPhoto && (
        <Hero
          artwork={heroArtwork}
          media={heroMedia}
          framedPhoto={framedPhoto}
        />
      )}

      {/* 2 — proof of craft, and dwell time */}
      <MotionSection />

      {/* 3 — "what would my name look like" */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24">
        <Reveal>
          <SectionHeading
            kicker="singleKicker"
            title="singleTitle"
            body="singleBody"
          />
        </Reveal>

        <ul className="mt-10 grid grid-cols-2 gap-x-4 gap-y-8 sm:gap-x-6 lg:grid-cols-4">
          {singles.map((artwork, i) => {
            const media = getMedia(artwork.id);
            if (!media) return null;
            return (
              <Reveal as="li" key={artwork.id} delay={i * 70}>
                <ArtworkCard
                  artwork={artwork}
                  media={media}
                  sizes={GRID_SIZES}
                />
              </Reveal>
            );
          })}
        </ul>
      </section>

      {/* The rest of the signature line */}
      {couples.length > 0 && (
        <section className="border-y border-bone bg-mist/45 py-16 sm:py-24">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <Reveal>
              <SectionHeading kicker="navCouple" title="galleryTitle" />
            </Reveal>

            <ul className="mt-10 grid grid-cols-2 gap-x-4 gap-y-8 sm:gap-x-6 lg:grid-cols-3">
              {couples.map((artwork, i) => {
                const media = getMedia(artwork.id);
                if (!media) return null;
                return (
                  <Reveal as="li" key={artwork.id} delay={i * 70}>
                    <ArtworkCard
                      artwork={artwork}
                      media={media}
                      sizes="(min-width: 1024px) 340px, (min-width: 640px) 44vw, 88vw"
                    />
                  </Reveal>
                );
              })}
            </ul>
          </div>
        </section>
      )}

      {/* The line that sells without him at the desk */}
      {words.length > 0 && (
        <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24">
          <Reveal>
            <SectionHeading
              kicker="wordKicker"
              title="wordTitle"
              body="wordBody"
            />
          </Reveal>

          <ul className="mt-10 grid grid-cols-2 gap-x-4 gap-y-8 sm:gap-x-6 lg:grid-cols-3">
            {words.map((artwork, i) => {
              const media = getMedia(artwork.id);
              if (!media) return null;
              return (
                <Reveal as="li" key={artwork.id} delay={i * 70}>
                  <ArtworkCard
                    artwork={artwork}
                    media={media}
                    sizes="(min-width: 1024px) 340px, (min-width: 640px) 44vw, 88vw"
                  />
                </Reveal>
              );
            })}
          </ul>

          <div className="mt-12 text-center">
            <Link
              href="/gallery"
              className="inline-block rounded-full border border-ink/20 px-7 py-3.5 text-sm text-ink transition-colors hover:border-ink/50"
            >
              <UiLabel k="heroSecondary" />
            </Link>
          </div>
        </section>
      )}

      <CtaBand />
    </>
  );
}
